# Default values for cofide-connect.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  registry: 010438484483.dkr.ecr.eu-west-1.amazonaws.com
  repository: cofide/connect-api
  pullPolicy: Always
  tag: ""

connect:
  urlBase: ""
  allowedOrigins: []
  insecureServerAddress:
    host: ""
    port: 51106
  adsServerAddress: :18000
  spiffeEndpointSocket: unix:///spiffe-workload-api/spire-agent.sock
  s3UseOidc: true
  awsRegion: ""
  iamRoleArn: ""
  oidcProviderAudience: ""
  s3TrustBundleStoreBucket: ""
  connectPsatAudience: ""
  trustDomain: ""
  valkeyAddress: valkey.connect.svc.cluster.local:6379
  connectTrustBundleStoreUrl: ""
  sqlConnectionString: ""
  sqlRemoteSpiffeId: ""
  telemetryEnabled: false
  authzPolicyEngine: "opa"
  initialRbac:
    version: 0
    roleBindings: []
  # Additional environment variables to pass to connect api binary.
  # For example:
  #  extraEnv:
  #  - name: SOME_VAR
  #    value: 'some value'
  extraEnv: []

envoy:
  image: "envoyproxy/envoy:v1.33-latest"
  imagePullPolicy: Always
  auth:
    issuer: ""
    tlsSecretName: ""
    # if empty, defaults to `["https://connect.{{ .Values.connect.urlBase }}"]`
    audiences: []
  logLevel: "info"
  securityContext: {}
  resources: {}


# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

service:
  annotations: {}
  type: LoadBalancer
  port: 8443

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
