# Default values for cofide-connect.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/.
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/.
image:
  registry: 010438484483.dkr.ecr.eu-west-1.amazonaws.com
  repository: cofide/connect-api
  pullPolicy: Always
  # Defaults to chart appVersion if not set.
  tag: ""

connect:
  # Base URL for envoy.
  urlBase: ""
  # Allowed origins for CORS requests.
  allowedOrigins: []
  # Host and port the API server listens on internally.
  # This port is not exposed on the pod itself, it is the port the envoy-sidecar sends requests to for connect.{{ .Values.connect.urlBase }} and connect-agent.{{ .Values.connect.urlBase }} SNI hostname matches.
  # Healthchecks are also served on this port.
  insecureServerAddress:
    host: ""
    port: 51106
  # Host and port the Aggregated Discovery Service listens on internally (used by workload clusters to get federated services).
  # This port is not exposed on the pod itself, it is the port the envoy-sidecar sends requests to for xds.{{ .Values.connect.urlBase }} SNI hostname matches.
  adsServerAddress:
    host: ""
    port: 18000
  # Workload API exposed by in-cluster SPIRE.
  spiffeEndpointSocket: unix:///spiffe-workload-api/spire-agent.sock
  # Configuration of the trust bundle store backend to use. Only one backend may be enabled.
  trustBundleStoreBackend:
    # Configuration for S3 trust bundle store backend.
    s3:
      # True to enable the S3 backend.
      enabled: true
      # Name of bucket to use as trust bundle store.
      bucket: ""
      # Configuration to use OIDC to access S3, exchanging the Connect server's SVID for AWS credentials.
      oidc:
        # True to use OIDC with the server's SVID to get temporary credentials to access S3 using OIDC, otherwise the AWS credentials will be sourced from the environment.
        enabled: true
        # Region to set in the AWS config when obtaining credentials through OIDC.
        awsRegion: ""
        # ARN of AWS role to assume when obtaining credentials through OIDC.
        iamRoleARN: ""
        # Audience expected by the OIDC provider in AWS.
        audience: ""
    # Configuration for GCS trust bundle store backend.
    gcs:
      # True to enable the GCS backend.
      enabled: false
      # Name of bucket to use as trust bundle store.
      bucket: ""
      # Configuration to use OIDC to access GCS, exchanging the Connect server's SVID for GCP credentials.
      oidc:
        # True to use OIDC with the server's SVID to get temporary credentials to access GCS using OIDC, otherwise the GCP credentials will be sourced from the environment.
        enabled: true
        # Fully qualified identifier of GCP workload identity provider to use when obtaining credentials through OIDC.
        # Must be in the form projects/PROJECT_ID/locations/global/workloadIdentityPools/WORKLOAD_IDENTITY_POOL_NAME/providers/WORKLOAD_IDENTITY_PROVIDER_NAME.
        workloadIdentityProvider: ""
        # Audience expected by the OIDC provider in GCP.
        audience: ""
  # Configuration of the datastore used by Connect
  datastore:
    sqlConnectionString:
      # True to enable using a SQL connection string to connect to the datastore
      enabled: true
      # SQL connection string for SQLite or Postgres database. SQLite should only be used for non-production workloads.
      # A username/password can be included in this connection string to connect to databases that do not support mTLS.
      connectionString: ""
      # For databases that support mTLS this is the SPIFFE ID that Connect will expect to be presented
      remoteSPIFFEID: ""
    cloudSQL:
      # True to enable Google CloudSQL as the datastore
      enabled: false
      # CloudSQL database instance to use
      # Format project_name:region:instance_name
      instance: ""
      # Name of the Connect database
      databaseName: "connect-db"
      # Configuration to use OIDC to access Google CloudSQL, exchanging server's SVID for a SA impersonation token 
      oidc:
        # Fully qualified identifier of GCP workload identity provider to use when obtaining credentials through OIDC.
        # Must be in the form projects/PROJECT_ID/locations/global/workloadIdentityPools/WORKLOAD_IDENTITY_POOL_NAME/providers/WORKLOAD_IDENTITY_PROVIDER_NAME.
        workloadIdentityProvider: ""
        # Audience expected by the OIDC provider in GCP
        audience: ""
        # Name of service account with access privileges to the Connect database in CloudSQL
        serviceAccountName: ""
  # Expected audience from OIDC token from Cofide SPIRE server in workload clusters.
  connectPSATAudience: ""
  # Trust domain of in-cluster SPIRE server.
  trustDomain: ""
  # URL trust bundle store is available at.
  connectTrustBundleStoreURL: ""
  # Whether to enable the open telemetry metrics server - exposed on port 4317.
  telemetryEnabled: false
  # Authz policy engine to use. Valid values: opa, none. "none" disables authz and is not suitable for production.
  authzPolicyEngine: "opa"
  # Initial RBAC configuration to bootstrap the server with. The initial configuration can be changed later through the API.
  initialRBAC:
    # Version of the initial RBAC configuration, >= 0. Will not be applied if 0 or at an equal or lower version to the last applied configuration.
    # Bump this to re-apply the latest initial RBAC configuration, e.g. to get back in if you remove all admin access.
    version: 0
    # Initial role bindings to bootstrap the system with.
    # For example:
    #  roleBindings:
    #  - roleID: admin
    #    resourceType: Cluster
    #    resourceID: clusterA
    #    user:
    #      subject: clusterAadmin@example.com
    roleBindings: []
  # Additional environment variables to pass to connect api binary.
  # For example:
  #  extraEnv:
  #  - name: SOME_VAR
  #    value: 'some value'
  extraEnv: []

envoy:
  image: "envoyproxy/envoy:v1.33-latest"
  imagePullPolicy: Always
  auth:
    # Issuer of the IdP in use.
    issuer: ""
    # JWKS URI of the IdP in use. Only http and https schemes are supported. Setting custom port is not supported.
    jwksUri: ""
    # Name of secret in the same namespace containing the TLS private key and cert to be used with the domain Connect is exposed on.
    # This certificate must be valid for connect.{{ .Values.connect.urlBase }}, connect-agent.{{ .Values.connect.urlBase }} and xds.{{ .Values.connect.urlBase }}.
    tlsSecretName: ""
    # Audiences set in tokens from the IdP. If empty, defaults to `["https://connect.{{ .Values.connect.urlBase }}"]`
    audiences: []
  logLevel: "info"
  securityContext: {}
  resources: {}


# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

service:
  annotations: {}
  type: LoadBalancer
  port: 8443

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
