apiVersion: v2
name: spiffe-enable
description: Helm chart for the spiffe-enable admission webhook for Kubernetes
type: application

version: 0.1.8

appVersion: "v0.5.2"

maintainers:
  - name: Cofide
    url: https://cofide.io
